# damage player, who is muted and continue write
damage: 1
debug: false
notify:
    # enable notify to muted player
    enabled: true
    # show time in it
    time: true
add-permissions:
    # list of permissions, works only with PEX
    list:
# permission group for muted players, works only with PEX        
set-group:
# totally disable commands for muted user. Not recommended, of course
disable-commands: false

rep_patt:
    - ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞß¸àáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ¸~АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯЁабвгдежзийклмнопрстуфхцчшщъыьэюяё